image: maven:3-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy

install_skip_tests:
  stage: build
  script:
    - mvn -V $MAVEN_CLI_OPTS clean install -DskipTests
  except:
    - master
    - deploy

install:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean install

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean deploy
  only:
    - master
    - deploy